# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
  - job: test
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
      - checkout: self
        submodules: recursive
      - script: curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
        displayName: 'Install rustc'
      - script: |
          export PATH=$PATH:$HOME/.cargo/bin
          cargo build --verbose
        displayName: 'Build'
      - script: |
          export PATH=$PATH:$HOME/.cargo/bin
          cargo test --verbose -- --test-threads=1
        displayName: 'Test'
