# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
  - job: test
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
      - checkout: self
        submodules: recursive
      - script: |
          #! /bin/bash
          # Make sure you grab the latest version
          curl -OL https://github.com/google/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip
          https://github.com/google/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip
          # Unzip
          unzip protoc-3.6.1-linux-x86_64.zip -d protoc3

          # Move protoc to /usr/local/bin/
          sudo mv protoc3/bin/* /usr/local/bin/

          # Move protoc3/include to /usr/local/include/
          sudo mv protoc3/include/* /usr/local/include/

          # Optional: change owner
          sudo chown $USER /usr/local/bin/protoc
          sudo chown -R $USER /usr/local/include/google
        displayName: 'Install protoc'
      - script: curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
        displayName: 'Install rustc'
      - script: |
          export PATH=$PATH:$HOME/.cargo/bin
          cargo build --verbose
        displayName: 'Build'
      - script: |
          export PATH=$PATH:$HOME/.cargo/bin
          RUST_BACKTRACE=1 cargo test --verbose -- --test-threads=1
        displayName: 'Test'
