[package]
name = "sqlite-commands"
version = "0.1.0"
authors = ["Mathias Lengler <mathmatze@googlemail.com>"]

[dependencies]
failure = "0.1.2"
serde = "1.0.71"
serde_derive = "1.0.71"
bincode = "1.0.1"

[dependencies.rusqlite]
version = "0.14.0"
features = ["bundled"]

[features]
default = []
blob = ["rusqlite/blob"]

[dev-dependencies]
tempfile = "3.0.3"
serde_json = "1.0.26"
bincode = "1.0.1"
